### ISSUE TITLE
SecGeoLookup DB not working 

### ISSUE THREAD

**Issue by Dr-Lazarus-V2** [azurit/modsecurity-geoip-plugin#2]
I have tried to use this plugin with the following docker image: https://hub.docker.com/layers/owasp/modsecurity-crs/4.5.0-nginx-202407300107/images/sha256-bc8c1820540a166fa258a90d9441307847da1d23823c674ace0c43a3e675cf35

However SecGoeLookupDB does not seem to work, thereby the plugin also does not seem to work.

**Comment by azurit** [comment]
Duplicate of https://github.com/coreruleset/modsecurity-crs-docker/issues/286.
